# Generated by Django 3.2 on 2023-02-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False)),
                ('name', models.CharField(max_length=200)),
                ('deadline', models.DateField()),
                ('status', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todo List',
                'ordering': ('-created_at',),
            },
        ),
    ]
